### ISSUE TITLE
Unable to install App with this depencency in XCode 15.3

### ISSUE THREAD

**Issue by pa-rw** [EWC-consortium/eudi-wallet-oid4vc-ios#11]
https://github.com/EWC-consortium/eudi-wallet-oid4vc-ios/blob/5b7a506878b9facc18f2185f8ad6b39b28b2df83/Package.swift#L19

Due to this issue: https://github.com/decentralised-dataexchange/PresentationExchangeSdkiOS/issues/1

**Comment by georgepadayatti** [comment]
Will be checking this and revert.

**Comment by josmilan** [comment]
This is fixed in 2024.8.1 release
